"""initial schema

Revision ID: ba63e5e4254f
Revises:
Create Date: 2026-10-01 18:33:28.115105
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ba63e5e4254f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "group",
            sa.Enum(
                "essential",
                "non_essential",
                "charges",
                "income",
                "movement",
                "review",
                name="category_group",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "kind",
            sa.Enum(
                "expense", "income", "neutral", name="category_kind", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("monthly_budget_cents", sa.BigInteger(), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.CheckConstraint(
            "kind IN ('expense', 'income', 'neutral')", name=op.f("ck_categories_category_kind")
        ),
        sa.CheckConstraint(
            "\"group\" IN ('essential', 'non_essential', 'charges', 'income', 'movement', 'review')",
            name=op.f("ck_categories_category_group"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("slug", name=op.f("uq_categories_slug")),
    )
    op.create_table(
        "institutions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("group_slug", sa.String(length=64), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("image_id", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_institutions")),
        sa.UniqueConstraint("slug", name=op.f("uq_institutions_slug")),
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "checking",
                "credit_card",
                "investment",
                name="account_kind",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("institution_id", sa.String(length=32), nullable=False),
        sa.Column("nickname", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("image_id", sa.String(length=32), nullable=True),
        sa.CheckConstraint(
            "kind IN ('checking', 'credit_card', 'investment')",
            name=op.f("ck_accounts_account_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
            name=op.f("fk_accounts_institution_id_institutions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
    )
    op.create_table(
        "balance_anchors",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("account_id", sa.String(length=32), nullable=False),
        sa.Column("on_date", sa.Date(), nullable=False),
        sa.Column("balance_cents", sa.BigInteger(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_balance_anchors_account_id_accounts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_balance_anchors")),
        sa.UniqueConstraint("account_id", "on_date", name=op.f("uq_balance_anchors_account_id")),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("account_id", sa.String(length=32), nullable=False),
        sa.Column("posted_on", sa.Date(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "expense",
                "income",
                "refund",
                "transfer",
                name="transaction_kind",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("category_id", sa.String(length=32), nullable=False),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column("description_search", sa.String(length=300), nullable=False),
        sa.Column("is_recurring", sa.Boolean(), nullable=False),
        sa.Column("transfer_id", sa.String(length=32), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(kind = 'expense' AND amount_cents < 0) OR (kind IN ('income', 'refund') AND amount_cents > 0) OR (kind = 'transfer' AND amount_cents <> 0)",
            name=op.f("ck_transactions_sign_matches_kind"),
        ),
        sa.CheckConstraint(
            "kind IN ('expense', 'income', 'refund', 'transfer')",
            name=op.f("ck_transactions_transaction_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_transactions_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], name=op.f("fk_transactions_category_id_categories")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
    )
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_transactions_account_id_posted_on", ["account_id", "posted_on"], unique=False
        )
        batch_op.create_index(
            "ix_transactions_description_search_kind", ["description_search", "kind"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_transactions_posted_on"), ["posted_on"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_transactions_transfer_id"), ["transfer_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transactions_transfer_id"))
        batch_op.drop_index(batch_op.f("ix_transactions_posted_on"))
        batch_op.drop_index("ix_transactions_description_search_kind")
        batch_op.drop_index("ix_transactions_account_id_posted_on")

    op.drop_table("transactions")
    op.drop_table("balance_anchors")
    op.drop_table("accounts")
    op.drop_table("institutions")
    op.drop_table("categories")
    # ### end Alembic commands ###
