"""Ports: what the domain and application need from the outside world."""

import datetime as dt
from collections.abc import Sequence
from types import TracebackType
from typing import Protocol

from financas.domain.models import (
    Account,
    BalanceAnchor,
    Category,
    InstallmentPlan,
    Institution,
    InvestmentHolding,
    Statement,
    Transaction,
    TransactionKind,
)
from financas.domain.money import YearMonth


class Clock(Protocol):
    def today(self) -> dt.date: ...
    def now(self) -> dt.datetime: ...


class InstitutionRepository(Protocol):
    def add(self, institution: Institution) -> None: ...
    def update(self, institution: Institution) -> None: ...
    def get(self, institution_id: str) -> Institution | None: ...
    def get_by_slug(self, slug: str) -> Institution | None: ...
    def list_all(self) -> list[Institution]: ...


class AccountRepository(Protocol):
    def add(self, account: Account) -> None: ...
    def update(self, account: Account) -> None: ...
    def get(self, account_id: str) -> Account | None: ...
    def list_all(self) -> list[Account]: ...


class CategoryRepository(Protocol):
    def add(self, category: Category) -> None: ...
    def update(self, category: Category) -> None: ...
    def get(self, category_id: str) -> Category | None: ...
    def get_by_slug(self, slug: str) -> Category | None: ...
    def list_all(self) -> list[Category]: ...


class TransactionRepository(Protocol):
    def add_many(self, transactions: Sequence[Transaction]) -> None: ...
    def get(self, transaction_id: str) -> Transaction | None: ...
    def delete(self, transaction_id: str) -> None: ...
    def list_by_transfer(self, transfer_id: str) -> list[Transaction]: ...
    def list_between(
        self, start: dt.date, end: dt.date, account_id: str | None = None
    ) -> list[Transaction]:
        """Inclusive range, newest first (``posted_on`` desc, then insertion order)."""
        ...

    def list_for_competence(self, start: dt.date, end: dt.date) -> list[Transaction]:
        """Entries that count in ``[start, end]``: a card entry counts in its statement month,
        everything else in the month of ``posted_on``. Newest first."""
        ...

    def list_by_account(self, account_id: str) -> list[Transaction]: ...
    def list_by_statement(self, statement_id: str) -> list[Transaction]: ...
    def list_by_plan(self, plan_id: str) -> list[Transaction]: ...
    def update_amount(self, transaction_id: str, amount_cents: int) -> None: ...
    def set_statement(self, transaction_id: str, statement_id: str) -> None: ...
    def movements(self, account_id: str) -> list[tuple[dt.date, int]]: ...
    def movements_for_holding(self, holding_id: str) -> list[tuple[dt.date, int]]: ...
    def last_category_id(self, description_search: str, kind: TransactionKind) -> str | None: ...


class StatementRepository(Protocol):
    def add(self, statement: Statement) -> None: ...
    def update(self, statement: Statement) -> None: ...
    def get(self, statement_id: str) -> Statement | None: ...
    def get_by_card_month(self, account_id: str, month: YearMonth) -> Statement | None: ...
    def list_for_card(self, account_id: str) -> list[Statement]:
        """Oldest month first."""
        ...

    def list_all(self) -> list[Statement]: ...


class PlanRepository(Protocol):
    def add(self, plan: InstallmentPlan) -> None: ...
    def get(self, plan_id: str) -> InstallmentPlan | None: ...
    def delete(self, plan_id: str) -> None: ...
    def list_all(self) -> list[InstallmentPlan]: ...


class BalanceAnchorRepository(Protocol):
    def upsert(self, anchor: BalanceAnchor) -> None:
        """Insert, or replace the anchor of the same (account, date)."""
        ...

    def list_for_account(self, account_id: str) -> list[BalanceAnchor]:
        """Valuations of the whole account only (holding valuations are separate)."""
        ...

    def list_for_holding(self, holding_id: str) -> list[BalanceAnchor]: ...


class HoldingRepository(Protocol):
    def add(self, holding: InvestmentHolding) -> None: ...
    def update(self, holding: InvestmentHolding) -> None: ...
    def get(self, holding_id: str) -> InvestmentHolding | None: ...
    def list_all(self) -> list[InvestmentHolding]: ...
    def list_for_account(self, account_id: str) -> list[InvestmentHolding]: ...


class ImageStore(Protocol):
    def save(self, data: bytes) -> str:
        """Validate (type and size) and store; return the new ``image_id``."""
        ...

    def open(self, image_id: str) -> tuple[bytes, str] | None:
        """Return ``(bytes, image type)`` or ``None``."""
        ...

    def delete(self, image_id: str) -> None: ...


class Work(Protocol):
    """The repositories of one open unit of work, plus ``commit()``."""

    # Read-only properties: a mutable attribute is invariant, so no implementation would match.
    @property
    def institutions(self) -> InstitutionRepository: ...
    @property
    def accounts(self) -> AccountRepository: ...
    @property
    def categories(self) -> CategoryRepository: ...
    @property
    def transactions(self) -> TransactionRepository: ...
    @property
    def anchors(self) -> BalanceAnchorRepository: ...
    @property
    def statements(self) -> StatementRepository: ...
    @property
    def plans(self) -> PlanRepository: ...
    @property
    def holdings(self) -> HoldingRepository: ...

    def commit(self) -> None: ...


class UnitOfWork(Protocol):
    """One atomic unit of work. Leaving the ``with`` block without ``commit()`` rolls back."""

    def __enter__(self) -> Work: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...
