"""Ports: what the domain and application need from the outside world."""

import datetime as dt
from collections.abc import Sequence
from types import TracebackType
from typing import Protocol, Self

from financas.domain.models import (
    Account,
    BalanceAnchor,
    Category,
    Institution,
    Transaction,
    TransactionKind,
)


class Clock(Protocol):
    def today(self) -> dt.date: ...


class InstitutionRepository(Protocol):
    def add(self, institution: Institution) -> None: ...
    def update(self, institution: Institution) -> None: ...
    def get(self, institution_id: str) -> Institution | None: ...
    def get_by_slug(self, slug: str) -> Institution | None: ...
    def list_all(self) -> list[Institution]: ...


class AccountRepository(Protocol):
    def add(self, account: Account) -> None: ...
    def update(self, account: Account) -> None: ...
    def get(self, account_id: str) -> Account | None: ...
    def list_all(self) -> list[Account]: ...


class CategoryRepository(Protocol):
    def add(self, category: Category) -> None: ...
    def update(self, category: Category) -> None: ...
    def get(self, category_id: str) -> Category | None: ...
    def get_by_slug(self, slug: str) -> Category | None: ...
    def list_all(self) -> list[Category]: ...


class TransactionRepository(Protocol):
    def add_many(self, transactions: Sequence[Transaction]) -> None: ...
    def get(self, transaction_id: str) -> Transaction | None: ...
    def delete(self, transaction_id: str) -> None: ...
    def list_by_transfer(self, transfer_id: str) -> list[Transaction]: ...
    def list_between(
        self, start: dt.date, end: dt.date, account_id: str | None = None
    ) -> list[Transaction]:
        """Inclusive range, newest first (``posted_on`` desc, then insertion order)."""
        ...

    def movements(self, account_id: str) -> list[tuple[dt.date, int]]: ...
    def last_category_id(self, description_search: str, kind: TransactionKind) -> str | None: ...


class BalanceAnchorRepository(Protocol):
    def upsert(self, anchor: BalanceAnchor) -> None:
        """Insert, or replace the anchor of the same (account, date)."""
        ...

    def list_for_account(self, account_id: str) -> list[BalanceAnchor]: ...


class ImageStore(Protocol):
    def save(self, data: bytes) -> str:
        """Validate (type and size) and store; return the new ``image_id``."""
        ...

    def open(self, image_id: str) -> tuple[bytes, str] | None:
        """Return ``(bytes, image type)`` or ``None``."""
        ...

    def delete(self, image_id: str) -> None: ...


class UnitOfWork(Protocol):
    """One atomic unit of work. Leaving the ``with`` block without ``commit()`` rolls back."""

    institutions: InstitutionRepository
    accounts: AccountRepository
    categories: CategoryRepository
    transactions: TransactionRepository
    anchors: BalanceAnchorRepository

    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...
    def commit(self) -> None: ...
